variables:
  # For non-Kubernetes executors, we use tcp://docker:2375/
  DOCKER_HOST: tcp://docker:2375/

  # When using dind, it's wise to use the overlayfs driver for
  DOCKER_DRIVER: overlay2

services:
- name: docker:dind
  command:
  - "--insecure-registry=local-registry.i.ling.id.au"

stages:
- build

image: docker:latest

before_script:
- apk add --update --no-cache make
- docker info

build:
  stage: build
  tags:
  - docker=true
  only:
  - master
  script:
  - make build
  - make test
  - make push
