---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
data:
  user-data: |
    {{- .Values.userdata | nindent 4}}

