{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-secret
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
stringData:
  {{ .Values.secrets | toYaml | indent 2 | trim }}
{{- end }}