#!/bin/bash
#

SERIAL_SOCKET="/run/qemu-monitor"

if [ -e "${SERIAL_SOCKET}" ]; then
  echo "Press CTRL+O to exit the console"
  sleep 1
	socat file:`tty`,raw,echo=0,escape=0x0f UNIX-CONNECT:${SERIAL_SOCKET}
else
	echo "Serial socket does not exist"
fi
