#!/bin/bash
#

MONITOR_SOCKET="/run/qemu-monitor"

if [ -e "${MONITOR_SOCKET}" ]; then
	echo "Simulating power-button press: "
	echo system_powerdown | socat - UNIX-CONNECT:${MONITOR_SOCKET} 
else
	echo "Monitor socket does not exist."
fi
