#!/bin/bash
#
# Put exit-hooks here
. /vm/data/config

. /vm/data/config

if [ "${MONITOR_SOCKET}" == "" ]; then
  MONITOR_SOCKET="/run/qemu-monitor"
  echo "Using default qemu-monitor"
fi

if [ -e "${MONITOR_SOCKET}" ]; then
	echo "change ide0-cd1 /opt/virtio-drivers.iso" | socat - UNIX-CONNECT:/vm/monitor
else
	echo "Monitor socket does not exist."
fi

