#!/bin/bash
#
MONITOR_SOCKET="/run/qemu-monitor"

if [ -e "${MONITOR_SOCKET}" ]; then
	echo "change ide0-cd1 /opt/virtio-drivers.iso" | socat - UNIX-CONNECT:${MONITOR_SOCKET}
else
	echo "Monitor socket does not exist."
fi
