{{- if .Values.userdata -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  user-data: |
    {{- .Values.userdata | nindent 4}}
{{- end }}