{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
stringData:
  {{- range $key, $val := .Values.secrets }}
  {{ $key | replace "-" "_" }}: {{ $val | quote }}
  {{- end }}
{{- end }}