{{- if .Values.vnc_port -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-test
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-vm
  ports:
  - port: 5900
    targetPort: 5900
  type: LoadBalancer
{{- end }}