name: publish-helm

on:
  push:
    tags:
    - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: helm package
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.16.2
          kustomize: 3.2.3
          helm: 2.14.3
          command: |
            echo "Helm Package"

            yq w -i ./helm/qemu-vm/Chart.yaml version ${GITHUB_REF:10}
            yq w -i ./helm/qemu-vm/values.yaml image_tag ${GITHUB_REF:10}
            
            helm init --client-only
            helm lint ./helm/qemu-vm
            mkdir -p /github/home/pkg
            helm package ./helm/qemu-vm/ --destination /github/home/pkg/

            git checkout --force gh-pages
            mv /github/home/pkg/*.tgz .
            helm repo index . --url https://lnattrass.github.io/docker-qemu-vm/

      - name: Release gh-pages
        uses: docker://peaceiris/gh-pages:v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: .
